apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  selector:
    app: messaging_app
    version: blue   # Initially directs traffic to blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP