# Generated by Django 5.2.4 on 2025-07-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_parent_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='unread',
            field=models.BooleanField(default=True, help_text='Has the receiver read this message?'),
        ),
    ]
