# Generated by Django 5.2.4 on 2025-07-26 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_unread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='unread',
            new_name='read',
        ),
    ]
