name: Django CI

on:
  push:
    branches: [ "main" ]  # Or your main branch, e.g., "master"
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9  # Or your Python version
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up MySQL Database
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --exclude=migrations --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=migrations

    - name: Test with pytest
      run: |
        pytest --cov=. --cov-report xml  # Generate coverage data

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  #Optional: Upload coverage reports to codecov
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Upload coverage reports to Github
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml
    - name: Start MySQL
      run: |
        sudo systemctl start mysql
        # Check if MySQL is running
        sudo systemctl status mysql

    - name: Setup Database for Testing
      run: |
        mysql -u root -e "CREATE DATABASE IF NOT EXISTS db;"
        mysql -u root -e "GRANT ALL PRIVILEGES ON db.* TO 'django'@'localhost' IDENTIFIED BY 'kali;"
        mysql -u root -e "FLUSH PRIVILEGES;"

    - name: Configure Django Settings for Testing
      run: |
        echo "DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'MYSQL_DB':'ALX_prodev'
                'MYSQL_USER'='root'
                'MYSQL_PASSWORD':'kali'
                'MYSQL_HOST':'db'
                'MYSQL_ROOT_PASSWORD':'kali'
            }
        }" > settings_test.py
        echo "from .settings import * \nfrom .settings_test import *" >> myproject/settings.py #Replace myproject with your project name

    - name: Run Tests
      run: |
        python manage.py test --settings=myproject.settings #Replace myproject with your project name