apiVersion : apps/v1
kind : deployment
metadata: 
  name: messaging_app
  labels:
    app: messaging_app
    version: blue
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: messaging_app
        version: blue
    template:
      metadata:
        labels:
          app: messaging_app
          version: blue
      spec:
        containers:
          - name: docker-compose
            image: app:2.0
            ports:
              - containerPort: 8000
            imagePullPolicy: Always
            readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: messaging_app-service
# spec:
#   selector:
#     app: messaging_app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8000
#   type: ClusterIP


